# Generated by Django 3.2.6 on 2021-10-21 08:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('bio', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('BA', 'Batter'), ('BO', 'Bowler'), ('WK', 'Wicket Keeper'), ('AR', 'All Rounder')], default='AR', max_length=2)),
                ('batting_style', models.CharField(choices=[('LH', 'Left Handed'), ('RH', 'Right Handed')], default='RH', max_length=2)),
                ('bowling_style', models.CharField(choices=[('LF', 'Left Arm FAST'), ('LM', 'Left Arm Medium'), ('LO', 'Left Arm Offspin'), ('CM', 'Chinaman'), ('RO', 'Right Arm Offspin'), ('RL', 'Right Arm Legspin'), ('RM', 'Right Arm Medium'), ('RF', 'Right Arm Fast')], default='RF', max_length=2)),
                ('icc_ranking', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PAK', 'PAKISTAN'), ('IND', 'INDIA'), ('AUS', 'AUSTRALIA'), ('SA', 'SOUTH AFRICA'), ('BAN', 'BANGLADESH'), ('ENG', 'ENGLAND'), ('SL', 'SRILANKA'), ('WI', 'WEST INDIES'), ('ZIM', 'ZIMBABWE'), ('NZ', 'NEW ZEALAND')], max_length=3)),
                ('players', models.ManyToManyField(related_name='team_players', to='teams.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerVisitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
            ],
        ),
    ]
