# Generated by Django 3.2.6 on 2021-10-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('head_curator', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('result', models.CharField(choices=[('TB', 'Team A Won'), ('TA', 'Team B Won'), ('TI', 'Match was tied'), ('NR', 'No Result - Match was Abandoned.')], default='TB', max_length=2)),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='series.series')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team_a', to='teams.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team_b', to='teams.team')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.ground')),
            ],
        ),
    ]
